// Enum
import { NetatmoEventType } from '../enum/event-type.enum';

export const eventIconMap: Map<NetatmoEventType, string> = new Map([
  [NetatmoEventType.ANIMAL, 'paw'],
  [NetatmoEventType.VEHICLE, 'car'],
  [NetatmoEventType.MOVEMENT, 'rss'],
  [NetatmoEventType.HUMAN, 'walk'],
  [NetatmoEventType.PERSON, 'face-recognition'],
  [NetatmoEventType.PERSON_AWAY, 'home-export-outline'],
  [NetatmoEventType.TAG_BIG_MOVE, 'motion-sensor'],
  [NetatmoEventType.TAG_SMALL_MOVE, 'motion-sensor'],
  [NetatmoEventType.BOOT, 'power'],
  [NetatmoEventType.NEW_MODULE, 'toy-brick-plus'],
  [NetatmoEventType.MODULE_CONNECT, 'lan-connect'],
  [NetatmoEventType.MODULE_DISCONNECT, 'lan-disconnect'],
  [NetatmoEventType.MODULE_LOW_BATTERY, 'battery-low'],
  [NetatmoEventType.MODULE_END_UPDATE, 'cellphone-arrow-down'],
  [NetatmoEventType.CONNECTION, 'lan-connect'],
  [NetatmoEventType.DISCONNECTION, 'lan-disconnect'],
  [NetatmoEventType.ON, 'power'],
  [NetatmoEventType.OFF, 'power-cycle'],
  [NetatmoEventType.SD, 'sd'],
  [NetatmoEventType.ALIM, 'power-settings'],
  [NetatmoEventType.TAG_UNINSTALLED, 'toy-brick-remove'],
  [NetatmoEventType.TAG_OPEN, 'door-open'],
  [NetatmoEventType.HUSH, 'smoke-detector-variant'],
  [NetatmoEventType.SMOKE, 'fire-alert'],
  [NetatmoEventType.TAMPERED, 'smoke-detector-variant-alert'],
  [NetatmoEventType.WIFI_STATUS, 'wifi-sync'],
  [NetatmoEventType.BATTERY_STATUS, 'battery-low'],
  [NetatmoEventType.DETECTION_CHAMBER_STATUS, 'broom'],
  [NetatmoEventType.SOUND_TEST, 'volume-high'],
  [NetatmoEventType.SIREN_SOUNDING, 'car-brake-alert'],
  [NetatmoEventType.SIREN_TAMPERED, 'hand-back-left-off'],
  [NetatmoEventType.INCOMING_CALL, 'doorbell-video'],
  [NetatmoEventType.ACCEPTED_CALL, 'account-voice'],
  [NetatmoEventType.MISSED_CALL, 'call-missed'],
]);
